version: "3"
services:
    db:
        image: mariadb:10.4
        environment:
            - MYSQL_DATABASE=db_name
            - MYSQL_USER=db_user
            - MYSQL_PASSWORD=12345
            - MYSQL_ROOT_PASSWORD=root
        ports:
            - "3306:3306"
        volumes:
            - ../data/:/var/lib/mysql
    web:
        build: ./web
        ports:
            - "80:80"
        volumes:
            - ../app/:/var/www

